--- #YAML:1.0
name:               HTTP-Cache-Transparent
version:            1.1
abstract:           Cache the result of http get-requests persistently.
author:
    - Mattias Holmlund <u108@m1.holmlund.se>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    LWP:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
