# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTTP-Cache-Transparent
version:      0.6
version_from: lib/HTTP/Cache/Transparent.pm
installdirs:  site
requires:
    LWP:                           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
